language: go
go:
- 1.13.4

branches:
  only:
    - dev

env:
  - GO111MODULE=on

sudo: required

services:
  - docker


script:
  - docker build --tag maershov/default_team .
  - docker build -f ./session_microservice/Dockerfile.session .
  - docker build -f ./comments_microservice/Dockerfile.comments .

