language: go
go:
- 1.13.4

branches:
  only:
    - dev

env:
  - GO111MODULE=on

sudo: required

services:
  - docker


script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build --tag maershov/default_team .
  - docker build --tag maershov/default_team_session -f ./session_microservice/Dockerfile.session .
  - docker build --tag maershov/default_team_comment -f ./comments_microservice/Dockerfile.comments .
  - docker push maershov/default_team

