// Code generated by MockGen. DO NOT EDIT.
// Source: 2019_2_default_team/films (interfaces: UseCase)

// Package mocks is a generated GoMock package.
package mocks

import (
	models "2019_2_default_team/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// GetFilm mocks base method
func (m *MockUseCase) GetFilm(arg0 context.Context, arg1 *models.RequestProfileFilm) (models.ProfileFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilm", arg0, arg1)
	ret0, _ := ret[0].(models.ProfileFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilm indicates an expected call of GetFilm
func (mr *MockUseCaseMockRecorder) GetFilm(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilm", reflect.TypeOf((*MockUseCase)(nil).GetFilm), arg0, arg1)
}

// PostFilmUse mocks base method
func (m *MockUseCase) PostFilmUse(arg0 context.Context, arg1 *models.RegisterProfileFilm) (models.ProfileFilm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostFilmUse", arg0, arg1)
	ret0, _ := ret[0].(models.ProfileFilm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostFilmUse indicates an expected call of PostFilmUse
func (mr *MockUseCaseMockRecorder) PostFilmUse(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostFilmUse", reflect.TypeOf((*MockUseCase)(nil).PostFilmUse), arg0, arg1)
}

// PutFilm mocks base method
func (m *MockUseCase) PutFilm(arg0 context.Context, arg1 *models.ProfileFilm) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutFilm", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutFilm indicates an expected call of PutFilm
func (mr *MockUseCaseMockRecorder) PutFilm(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutFilm", reflect.TypeOf((*MockUseCase)(nil).PutFilm), arg0, arg1)
}
